apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-operator-crds
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.github: ""
    notifications.argoproj.io/subscribe.on-sync-failed.github: ""
spec:
  project: platform
  source:
    repoURL: https://github.com/tngsolution/namespace-operator
    targetRevision: main
    path: manifests/charts/namespace-operator/crds
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true